<nav>
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="product.php">Our Flight</a></li>
        <li><a href="enquire.php">Enquire</a></li>
        <li><a href="payment.php">Payment</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="enhancements.php">Enhancement</a></li>
        <li><a href="enhancements2.php">Enhancement 2</a></li>
        <li><a href="manage.php">Manage</a></li>
    </ul>
</nav>